const cases = [
  {system:'胸部', modality:'X-RAY', title:'自发性气胸', history:'23 岁男性，运动后突发右侧胸痛，伴轻度呼吸困难。', scan:'chest-scan', level:'中级', answer:1, options:['右下肺肺炎','右侧自发性气胸','大量胸腔积液','肺动脉栓塞'], explain:'右侧胸膜线清晰可见，其外周肺纹理消失，符合气胸的典型征象。'},
  {system:'神经', modality:'CT', title:'基底节区脑出血', history:'62 岁男性，高血压病史，突发左侧肢体无力 2 小时。', scan:'brain-scan', level:'入门', answer:2, options:['脑膜瘤','大脑中动脉梗死','右侧基底节区脑出血','硬膜下血肿'], explain:'右侧基底节区见高密度灶，并有轻度周围水肿，首先考虑急性脑出血。'},
  {system:'腹部', modality:'MRI', title:'肝海绵状血管瘤', history:'48 岁女性，体检发现肝右叶占位，无肝炎病史。', scan:'abdomen-scan', level:'进阶', answer:0, options:['肝血管瘤','肝细胞癌','肝脓肿','肝转移瘤'], explain:'病灶 T2 明显高信号，结合外周结节样强化、向心性填充，支持肝血管瘤。'},
  {system:'骨骼', modality:'X-RAY', title:'桡骨远端骨折', history:'71 岁女性，跌倒后手掌撑地，腕部肿痛畸形。', scan:'chest-scan', level:'入门', answer:3, options:['舟骨骨折','月骨脱位','尺骨茎突骨折','Colles 骨折'], explain:'桡骨远端骨折伴远端向背侧移位，为典型 Colles 骨折机制和表现。'}
];
let current=0, selected=null, tool='window', solved=Number(localStorage.getItem('yys-solved')||36), correct=Number(localStorage.getItem('yys-correct')||31);
let favorites=JSON.parse(localStorage.getItem('yys-favorites')||'[]'), completed=JSON.parse(localStorage.getItem('yys-completed')||'[]');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('.sidebar').classList.remove('open');scrollTo(0,0)}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('.menu').onclick=()=>$('.sidebar').classList.toggle('open');
function renderCases(filter='all',query=''){const list=cases.filter((c,i)=>(filter==='all'||c.system===filter||(filter==='favorite'&&favorites.includes(i)))&&(`${c.title}${c.system}${c.modality}`.toLowerCase().includes(query.toLowerCase())));$('#caseList').innerHTML=list.map(c=>{const i=cases.indexOf(c);return `<article class="case-item ${completed.includes(i)?'completed':''}" data-case="${i}"><div class="case-thumb ${c.scan}"></div><div><small>${favorites.includes(i)?'★ ':''}${c.system} · ${c.modality} · ${c.level}</small><h3>${c.title}</h3><p>${c.history}</p></div><span class="arrow">→</span></article>`}).join('')||'<div class="empty-state"><b>这里还没有病例</b><p>收藏病例后，可以在这里集中复习。</p></div>';$$('.case-item').forEach(el=>el.onclick=()=>openCase(+el.dataset.case))}
renderCases();
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCases(b.dataset.filter,$('#globalSearch').value)});
$('#globalSearch').oninput=e=>{showView('cases');renderCases($('.filters .active').dataset.filter,e.target.value)};
function openCase(i){current=i;selected=null;const c=cases[i];showView('viewer');$('#viewerTitle').textContent=c.title;$('#viewerIndex').textContent=`病例 ${String(i+1).padStart(2,'0')} / ${String(cases.length).padStart(2,'0')}`;$('#caseHistory').textContent=c.history;$('#activeScan').className=`scan large ${c.scan}`;$('#answers').innerHTML=c.options.map((o,j)=>`<div class="answer" data-answer="${j}"><i></i>${o}</div>`).join('');$$('.answer').forEach(a=>a.onclick=()=>{selected=+a.dataset.answer;$$('.answer').forEach(x=>x.classList.toggle('selected',x===a))});$('#feedback').className='feedback';$('#feedback').textContent='';$('#submitAnswer').style.display='block';$('#nextCase').style.display='none';$('#caseNote').value=localStorage.getItem(`yys-note-${i}`)||'';updateFavorite();resetImage()}
$$('[data-open-case]').forEach(el=>el.onclick=()=>openCase(+el.dataset.openCase));
$('#submitAnswer').onclick=()=>{if(selected===null){$('#feedback').className='feedback wrong';$('#feedback').textContent='请先选择一个诊断。';return}const c=cases[current],ok=selected===c.answer;$('#feedback').className=`feedback ${ok?'correct':'wrong'}`;$('#feedback').textContent=`${ok?'判断正确。':'还差一点。'} ${c.explain}`;$$('.answer').forEach((a,i)=>{if(i===c.answer)a.classList.add('correct-answer');else if(i===selected)a.classList.add('wrong-answer')});if(!completed.includes(current)){solved++;if(ok)correct++;completed.push(current);localStorage.setItem('yys-completed',JSON.stringify(completed));localStorage.setItem('yys-solved',solved);localStorage.setItem('yys-correct',correct)}updateStats();$('#submitAnswer').style.display='none';$('#nextCase').style.display='block'};
$('#nextCase').onclick=()=>openCase((current+1)%cases.length);
$('#randomCase').onclick=()=>openCase(Math.floor(Math.random()*cases.length));
function updateFavorite(){const saved=favorites.includes(current);$('#favoriteCase').textContent=saved?'★ 已收藏':'☆ 收藏';$('#favoriteCase').classList.toggle('saved',saved)}
$('#favoriteCase').onclick=()=>{favorites=favorites.includes(current)?favorites.filter(i=>i!==current):[...favorites,current];localStorage.setItem('yys-favorites',JSON.stringify(favorites));updateFavorite()};
let noteTimer;$('#caseNote').oninput=e=>{clearTimeout(noteTimer);$('#noteSaved').textContent='保存中…';noteTimer=setTimeout(()=>{localStorage.setItem(`yys-note-${current}`,e.target.value);$('#noteSaved').textContent='已保存'},350)};
function updateStats(){$('#solvedCount').textContent=solved;$('#accuracy').textContent=Math.round(correct/solved*100)+'%'}updateStats();
$$('.tool').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;$$('.tool').forEach(x=>x.classList.toggle('active',x===b));if(tool==='invert'){$('#activeScan').style.filter=$('#activeScan').style.filter.includes('invert')?'':'invert(1)';tool='window'}});
let zoom=1,ww=1500,wl=-600;
$('#viewport').onwheel=e=>{e.preventDefault();if(tool==='zoom'){zoom=Math.max(.6,Math.min(2.4,zoom-e.deltaY*.001));$('#activeScan').style.transform=`scale(${zoom})`}else{ww=Math.max(200,Math.min(2500,ww-e.deltaY));$('#ww').textContent=Math.round(ww);$('#activeScan').style.filter=`contrast(${1500/ww}) brightness(${1+(wl+600)/1000})`}};
$('#viewport').onclick=e=>{if(tool!=='annotate'||e.target.closest('.tools'))return;const r=$('#viewport').getBoundingClientRect(),a=document.createElement('i');a.className='annotation';a.style.left=((e.clientX-r.left)/r.width*100)+'%';a.style.top=((e.clientY-r.top)/r.height*100)+'%';$('#viewport').appendChild(a)};
function resetImage(){zoom=1;ww=1500;wl=-600;$('#ww').textContent=ww;$('#wl').textContent='−600';$('#activeScan').style='';$$('.annotation').forEach(a=>a.remove())}$('#resetViewer').onclick=resetImage;
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#globalSearch').focus()}if(!$('#viewer').classList.contains('active')||e.target.matches('input,textarea'))return;if(e.key==='ArrowRight')openCase((current+1)%cases.length);if(e.key.toLowerCase()==='a')$('.tool[data-tool="annotate"]').click();if(e.key.toLowerCase()==='r')resetImage();if(['1','2','3','4'].includes(e.key)){const a=$(`.answer[data-answer="${+e.key-1}"]`);if(a)a.click()}});
