const cases = CASES, storagePrefix='yys-honest-v1';
let current=0, selected=null, tool='window';
let favorites=JSON.parse(localStorage.getItem(`${storagePrefix}-favorites`)||'[]').filter(i=>i>=0&&i<cases.length);
let completed=JSON.parse(localStorage.getItem(`${storagePrefix}-completed`)||'[]').filter(i=>i>=0&&i<cases.length);
let solved=completed.length, correct=Math.min(Number(localStorage.getItem(`${storagePrefix}-correct`)||0),solved);
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('.sidebar').classList.remove('open');scrollTo(0,0)}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('.menu').onclick=()=>$('.sidebar').classList.toggle('open');
function renderCases(filter='all',query=''){const list=cases.filter((c,i)=>(filter==='all'||c.system===filter||(filter==='favorite'&&favorites.includes(i)))&&(`${c.title}${c.system}${c.modality}`.toLowerCase().includes(query.toLowerCase())));$('#caseList').innerHTML=list.map(c=>{const i=cases.indexOf(c);return `<article class="case-item ${completed.includes(i)?'completed':''}" data-case="${i}"><img class="case-thumb" src="${c.image}" alt="${c.title}影像"><div><small>${favorites.includes(i)?'★ ':''}${c.system} · ${c.modality} · ${c.level}</small><h3>${c.title}</h3><p>${c.history}</p></div><span class="arrow">→</span></article>`}).join('')||'<div class="empty-state"><b>这里还没有病例</b><p>收藏病例后，可以在这里集中复习。</p></div>';$$('.case-item').forEach(el=>el.onclick=()=>openCase(+el.dataset.case))}
renderCases();
$('#caseTotal').textContent=cases.length;
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCases(b.dataset.filter,$('#globalSearch').value)});
$('#globalSearch').oninput=e=>{showView('cases');renderCases($('.filters .active').dataset.filter,e.target.value)};
function openCase(i){current=i;selected=null;const c=cases[i];showView('viewer');$('#viewerTitle').textContent=c.title;$('#viewerIndex').textContent=`病例 ${String(i+1).padStart(2,'0')} / ${String(cases.length).padStart(2,'0')}`;$('#caseHistory').textContent=c.history;$('#viewerModality').textContent=c.modality;$('#activeScan').src=c.image;$('#activeScan').alt=c.title+'医学影像';$('#imageCredit').textContent=`${c.source} · ${c.license}`;$('#imageCredit').href=c.sourceUrl;$('#answers').innerHTML=c.options.map((o,j)=>`<div class="answer" data-answer="${j}"><i></i>${o}</div>`).join('');$$('.answer').forEach(a=>a.onclick=()=>{selected=+a.dataset.answer;$$('.answer').forEach(x=>x.classList.toggle('selected',x===a))});$('#feedback').className='feedback';$('#feedback').textContent='';$('#learningReveal').innerHTML='';$('#submitAnswer').style.display='block';$('#nextCase').style.display='none';$('#caseNote').value=localStorage.getItem(`${storagePrefix}-note-${i}`)||'';updateFavorite();resetImage()}
$$('[data-open-case]').forEach(el=>el.onclick=()=>openCase(+el.dataset.openCase));
$('#submitAnswer').onclick=()=>{if(selected===null){$('#feedback').className='feedback wrong';$('#feedback').textContent='请先选择一个诊断。';return}const c=cases[current],ok=selected===c.answer;$('#feedback').className=`feedback ${ok?'correct':'wrong'}`;$('#feedback').textContent=`${ok?'判断正确。':'还差一点。'} ${c.explain}`;$$('.answer').forEach((a,i)=>{if(i===c.answer)a.classList.add('correct-answer');else if(i===selected)a.classList.add('wrong-answer')});$('#learningReveal').innerHTML=`<section><b>关键影像征象</b><ul>${c.findings.map(x=>`<li>${x}</li>`).join('')}</ul></section><details><summary>鉴别诊断</summary><p>${c.differential}</p></details><details><summary>阅片要点</summary><p>${c.pearl}</p></details><details><summary>结构化报告示例</summary><p>${c.report}</p></details>`;if(!completed.includes(current)){if(ok)correct++;completed.push(current);solved=completed.length;localStorage.setItem(`${storagePrefix}-completed`,JSON.stringify(completed));localStorage.setItem(`${storagePrefix}-correct`,correct)}updateStats();renderCases($('.filters .active').dataset.filter,$('#globalSearch').value);$('#submitAnswer').style.display='none';$('#nextCase').style.display='block'};
$('#nextCase').onclick=()=>openCase((current+1)%cases.length);
$('#randomCase').onclick=()=>openCase(Math.floor(Math.random()*cases.length));
function updateFavorite(){const saved=favorites.includes(current);$('#favoriteCase').textContent=saved?'★ 已收藏':'☆ 收藏';$('#favoriteCase').classList.toggle('saved',saved)}
$('#favoriteCase').onclick=()=>{favorites=favorites.includes(current)?favorites.filter(i=>i!==current):[...favorites,current];localStorage.setItem(`${storagePrefix}-favorites`,JSON.stringify(favorites));updateFavorite();updateStats()};
let noteTimer;$('#caseNote').oninput=e=>{clearTimeout(noteTimer);$('#noteSaved').textContent='保存中…';noteTimer=setTimeout(()=>{const key=`${storagePrefix}-note-${current}`;if(e.target.value.trim())localStorage.setItem(key,e.target.value);else localStorage.removeItem(key);$('#noteSaved').textContent='已保存';updateStats()},350)};
function updateStats(){solved=completed.length;$('#solvedCount').textContent=solved;$('#accuracy').textContent=solved?Math.round(correct/solved*100)+'%':'—';$('#favoriteCount').textContent=favorites.length;const notes=cases.filter((_,i)=>(localStorage.getItem(`${storagePrefix}-note-${i}`)||'').trim()).length;$('#noteCount').textContent=notes;$('#dailyCount').textContent=solved;$('#sideTotal').textContent=cases.length;$('#sideProgress').style.width=(solved/cases.length*100)+'%';$$('.master-row').forEach(row=>{const system=row.dataset.system,total=cases.filter(c=>c.system===system).length,done=completed.filter(i=>cases[i]?.system===system).length;row.querySelector('i').style.width=(done/total*100)+'%';row.querySelector('span').textContent=`${done} / ${total}`})}updateStats();
$$('.tool').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;$$('.tool').forEach(x=>x.classList.toggle('active',x===b));if(tool==='invert'){$('#activeScan').style.filter=$('#activeScan').style.filter.includes('invert')?'':'invert(1)';tool='window'}});
let zoom=1,ww=1500,wl=-600;
$('#viewport').onwheel=e=>{e.preventDefault();if(tool==='zoom'){zoom=Math.max(.6,Math.min(2.4,zoom-e.deltaY*.001));$('#activeScan').style.transform=`translate(-50%,-50%) scale(${zoom})`}else{ww=Math.max(200,Math.min(2500,ww-e.deltaY));$('#ww').textContent=Math.round(ww);$('#activeScan').style.filter=`contrast(${1500/ww}) brightness(${1+(wl+600)/1000})`}};
$('#viewport').onclick=e=>{if(tool!=='annotate'||e.target.closest('.tools'))return;const r=$('#viewport').getBoundingClientRect(),a=document.createElement('i');a.className='annotation';a.style.left=((e.clientX-r.left)/r.width*100)+'%';a.style.top=((e.clientY-r.top)/r.height*100)+'%';$('#viewport').appendChild(a)};
function resetImage(){zoom=1;ww=1500;wl=-600;$('#ww').textContent=ww;$('#wl').textContent='−600';$('#activeScan').style='';$$('.annotation').forEach(a=>a.remove())}$('#resetViewer').onclick=resetImage;
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#globalSearch').focus()}if(!$('#viewer').classList.contains('active')||e.target.matches('input,textarea'))return;if(e.key==='ArrowRight')openCase((current+1)%cases.length);if(e.key.toLowerCase()==='a')$('.tool[data-tool="annotate"]').click();if(e.key.toLowerCase()==='r')resetImage();if(['1','2','3','4'].includes(e.key)){const a=$(`.answer[data-answer="${+e.key-1}"]`);if(a)a.click()}});
const linkedCase=Number(new URLSearchParams(location.search).get('case'));
if(new URLSearchParams(location.search).has('case')&&Number.isInteger(linkedCase)&&linkedCase>=0&&linkedCase<cases.length)openCase(linkedCase);else{openCase(0);showView('home')}
