const CASES = [
{system:'胸部',modality:'X-RAY',title:'右侧张力性气胸',history:'67 岁男性，突发呼吸困难、胸痛，血压下降。',image:'assets/images/pneumothorax.png',level:'入门',answer:1,options:['右肺大疱','右侧张力性气胸','右侧胸腔积液','右肺不张'],explain:'右侧胸腔明显透亮、肺纹理消失，右肺受压向肺门萎陷，并伴纵隔左移，符合张力性气胸。',findings:['右侧脏层胸膜线可见，线外肺纹理消失','右肺明显受压萎陷','纵隔及心影向左移位'],differential:'巨大肺大疱通常可见薄壁，纵隔移位不明显；皮肤皱褶线外仍可见肺纹理。',pearl:'张力性气胸是临床诊断。患者不稳定时不应等待影像检查才减压。',report:'右侧大量气胸伴纵隔左移，符合张力性气胸。建议立即临床处理。',source:'Wikimedia Commons · Hellerhoff',license:'CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:09-01-Pneumothorax.png'},
{system:'胸部',modality:'X-RAY',title:'心源性肺水肿',history:'76 岁男性，夜间阵发性呼吸困难，双下肢水肿。',image:'assets/images/pulmonary-edema.jpg',level:'入门',answer:0,options:['心源性肺水肿','双肺多灶感染','肺纤维化','气胸'],explain:'双肺弥漫性间质及肺泡性阴影、心影增大和左侧胸腔积液支持心源性肺水肿。',findings:['双肺弥漫性模糊肺泡及间质性阴影','心影增大','左侧肋膈角变钝，提示胸腔积液'],differential:'ARDS 通常心影不大；感染多呈局灶或不对称分布，需结合发热和炎症指标。',pearl:'判断肺水肿应同时观察心影、肺血流分布、间隔线和胸腔积液。',report:'双肺间质及肺泡性水肿，伴心影增大及左侧胸腔积液，符合充血性心力衰竭表现。',source:'Wikimedia Commons · Frank Gaillard',license:'CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Pulmonary_oedema.jpg'},
{system:'胸部',modality:'CTPA',title:'急性肺动脉栓塞',history:'54 岁女性，术后第 5 天突发胸闷、心动过速，D-二聚体升高。',image:'assets/images/pulmonary-embolism.jpg',level:'中级',answer:2,options:['主动脉夹层','肺炎','急性肺动脉栓塞','心包积液'],explain:'双侧肺动脉内可见被对比剂包绕的低密度充盈缺损，为急性肺栓塞直接征象。',findings:['主肺动脉分叉及双侧肺动脉内充盈缺损','部分血栓周围可见对比剂环绕','需继续评估右心室大小及室间隔形态'],differential:'流动伪影边缘较模糊，常见于上腔静脉邻近；慢性血栓多偏心并与血管壁成钝角。',pearl:'发现血栓后必须继续评估右心负荷和肺梗死，以支持风险分层。',report:'双侧肺动脉急性栓塞，累及主肺动脉分叉。建议结合右心功能和生物标志物进行风险分层。',source:'Wikimedia Commons · Rvahudson',license:'CC BY-SA 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:CTA_Chest_With_Massive_Pulmonary_Embolism_and_Complete_Occlusion.jpg'},
{system:'胸部',modality:'CT',title:'左下叶空洞性肺癌',history:'69 岁女性，咳嗽、体重下降，既往长期吸烟。',image:'assets/images/lung-cancer.png',level:'中级',answer:3,options:['肺脓肿','肺结核','肺隔离症','空洞性肺癌'],explain:'左下叶见厚壁不规则空洞性肿块，壁结节样增厚，恶性可能性高。',findings:['左下叶近肺门区软组织肿块','病灶内空洞形成，壁厚且不规则','邻近支气管受累'],differential:'肺脓肿常见液平和急性感染症状；结核空洞常位于上叶并伴卫星灶或树芽征。',pearl:'空洞壁越厚且越不规则，恶性风险越高，但最终仍需组织学确诊。',report:'左下叶空洞性肿块，影像高度怀疑原发性肺癌。建议增强 CT、分期检查及组织学取样。',source:'Wikimedia Commons · Jmarchn',license:'CC0',sourceUrl:'https://commons.wikimedia.org/wiki/File:CT_scan_of_lung_cancer_with_cavitation.png'},
{system:'神经',modality:'CT',title:'左侧基底节区脑出血',history:'62 岁男性，高血压病史，突发右侧肢体无力、失语。',image:'assets/images/basal-ganglia-hemorrhage.png',level:'入门',answer:2,options:['脑膜瘤','大脑中动脉梗死','左侧基底节区脑出血','硬膜下血肿'],explain:'左侧基底节区见高密度血肿并有周围水肿和占位效应。',findings:['左侧基底节区不规则高密度血肿','周围可见低密度水肿带','左侧侧脑室受压，正中结构右移'],differential:'钙化通常边界清楚且无水肿；出血性肿瘤常位置不典型并伴不成比例的水肿。',pearl:'描述脑出血要依次交代部位、大小、脑室破入、占位效应和脑疝征象。',report:'左侧基底节区急性脑出血，伴明显占位效应及轻度中线右移。',source:'Wikimedia Commons · Dahlqvist 等',license:'CC BY 2.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:CT_Scan_BGH.png'},
{system:'神经',modality:'CT',title:'急性硬膜外血肿',history:'19 岁男性，车祸后短暂清醒，随后意识水平下降。',image:'assets/images/epidural-hematoma.jpg',level:'入门',answer:0,options:['硬膜外血肿','硬膜下血肿','蛛网膜下腔出血','脑梗死'],explain:'左侧颞顶部双凸透镜形高密度影伴明显占位效应，符合硬膜外血肿。',findings:['左侧颞顶部双凸透镜形高密度影','血肿边界受颅缝限制','左侧侧脑室受压并伴中线右移'],differential:'硬膜下血肿通常呈新月形，可跨颅缝，但受硬膜反折限制。',pearl:'硬膜外血肿可快速扩大；显著占位效应和临床恶化需紧急神经外科处理。',report:'左侧急性硬膜外血肿，伴明显占位效应及中线右移。建议神经外科紧急会诊。',source:'Wikimedia Commons · James Heilman, MD',license:'CC BY-SA 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:EpiduralHematoma.jpg'},
{system:'神经',modality:'MRI',title:'多发性硬化斑块',history:'31 岁女性，反复视力下降与肢体麻木，本次症状加重。',image:'assets/images/multiple-sclerosis.jpg',level:'进阶',answer:3,options:['脑小血管病','脑转移瘤','偏头痛相关灶','多发性硬化'],explain:'DIR 轴位图像显示多发皮质旁及皮质病灶，分布支持脱髓鞘病变。',findings:['双侧大脑半球多发皮质旁高信号病灶','部分病灶累及皮质','病灶空间分布符合炎性脱髓鞘过程'],differential:'小血管病多位于深部白质，较少累及胼胝体下缘和皮质；转移瘤常伴显著水肿及强化。',pearl:'多发性硬化诊断核心是时间和空间多发，单张影像不能独立完成诊断。',report:'幕上多发皮质及皮质旁脱髓鞘样病灶，结合临床考虑多发性硬化；建议完整序列及增强评估活动性。',source:'Wikimedia Commons · Favaretto 等',license:'CC BY 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Axial_DIR_MRI_of_a_brain_with_multiple_sclerosis_lesions.jpg'},
{system:'腹部',modality:'MRI',title:'肝海绵状血管瘤',history:'48 岁女性，体检发现肝右叶占位，无肝炎病史。',image:'assets/images/liver-hemangioma.jpg',level:'中级',answer:0,options:['肝血管瘤','肝细胞癌','肝脓肿','肝转移瘤'],explain:'动态增强序列显示外周结节样强化并逐渐向中心填充，符合肝血管瘤。',findings:['边界清楚的肝内占位','早期外周不连续结节样强化','后期逐渐向心性填充'],differential:'HCC 常表现动脉期整体强化及后期廓清；转移瘤一般不呈典型血池样渐进填充。',pearl:'观察强化随时间变化的模式，比只看某一个时相更重要。',report:'肝内病灶呈典型渐进性向心填充，符合海绵状血管瘤。',source:'Wikimedia Commons · Nils Albiin',license:'CC BY 2.5',sourceUrl:'https://commons.wikimedia.org/wiki/File:Angioma_epatico-RM.jpg'},
{system:'腹部',modality:'CT',title:'急性阑尾炎',history:'27 岁男性，转移性右下腹痛伴恶心 12 小时。',image:'assets/images/appendicitis.jpg',level:'入门',answer:1,options:['盲肠憩室炎','急性阑尾炎','末端回肠炎','输尿管结石'],explain:'右下腹阑尾明显增粗，测量约 17 mm，并伴周围炎性改变。',findings:['阑尾直径明显增大，约 17 mm','阑尾壁增厚','阑尾周围脂肪间隙模糊'],differential:'盲肠憩室炎的炎症中心位于憩室；末端回肠炎表现为较长节段肠壁增厚。',pearl:'阑尾直径大于 6 mm 不能单独诊断，必须结合壁改变和周围炎症。',report:'CT 表现符合急性阑尾炎，未见明确脓肿或游离气体。',source:'Wikimedia Commons · James Heilman, MD',license:'CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:CAT_scan_demonstrating_acute_appendicitis.jpg'},
{system:'骨骼',modality:'X-RAY',title:'桡骨远端 Colles 骨折',history:'71 岁女性，跌倒后手掌撑地，腕部肿痛畸形。',image:'assets/images/colles-fracture.jpg',level:'入门',answer:3,options:['舟骨骨折','月骨脱位','Smith 骨折','Colles 骨折'],explain:'桡骨远端骨折伴远端骨块向背侧移位和成角，符合 Colles 骨折。',findings:['桡骨远端干骺端骨折','远端骨块背侧移位及背侧成角','可见桡骨高度下降'],differential:'Smith 骨折的远端骨块向掌侧移位；Barton 骨折累及关节面并伴腕骨脱位。',pearl:'报告应描述关节面受累、移位方向、桡骨高度和倾斜角。',report:'左侧桡骨远端 Colles 型骨折，伴背侧成角及轻度短缩。',source:'Wikimedia Commons · Lucien Monfils',license:'CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Collesfracture.jpg'}
];
