import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import vm from 'node:vm';
const ROOT=path.resolve(import.meta.dirname,'..');
const fresh=JSON.parse(await fs.readFile(path.join(ROOT,'data','next-200-candidates.json'),'utf8')).topics;
const alternates=JSON.parse(await fs.readFile(path.join(ROOT,'data','existing-alternate-candidates.json'),'utf8')).topics;
const manifestPath=path.join(ROOT,'data','expanded-case-sources.json');const manifest=JSON.parse(await fs.readFile(manifestPath,'utf8'));manifest.records=manifest.records.slice(0,486);manifest.count=manifest.records.length;
const rows=(system,items)=>items.map(row=>({system,...row}));
const PICKS=[
...rows('胸部',[
{n:'pulmonary-hypertension',f:'File:Schwere pulmonale Hypertonie 51W - CR pa - 001.jpg',t:'重度肺动脉高压胸片'},
{n:'pulmonary-hypertension',f:'File:Ausgepraegte pulmonale Hypertonie im Roentgenbild und in der CT 64M - CR pa und CT - 001.jpg',t:'肺动脉高压X线与CT对照'},
{n:'asd',f:'File:Vorhofseptumdefekt mit Verschlusssystem 84W - CR pa - 001.jpg',t:'房间隔缺损封堵器胸片'},
{n:'asd',f:'File:Verschlusssystem fuer PFO-ASD-Verschluss im Thorax-Roentgenbild 54W - CR pa - 001.jpg',t:'PFO/房间隔缺损封堵术后胸片'},
{n:'asd',f:'File:ASD mit interventionellem Verschluss 77W - CR pa - 001.jpg',t:'房间隔缺损介入封堵术后影像'},
{n:'pda',f:'File:Residuum eines offenen Ductus arterious - CT axial 001.jpg',t:'动脉导管未闭残余交通'},
{n:'constrictive-pericarditis',f:'File:Pericarditis constrictiva mit massiven Verkalkungen 73W - CR - 001.jpg',t:'钙化性缩窄性心包炎'},
{n:'thoracic-aortic-aneurysm',f:'File:CTAnurysmT.PNG',t:'胸主动脉瘤CT'},
{n:'thoracic-aortic-aneurysm',f:'File:CTRupturedTA.PNG',t:'胸主动脉瘤破裂'},
{n:'airway-foreign-body',f:'File:Fremdkoerperaspiration mit Ventilwirkung 2W - CR ap - 001.jpg',t:'气道异物伴活瓣性阻塞'},
{n:'airway-foreign-body',f:'File:Foreign body aspiration.jpg',t:'儿童食管硬币异物胸片'},
{n:'cpam',f:'File:CPAM linke Lunge im Erwachsenenalter 58W - CT - 001.jpg',t:'成人先天性肺气道畸形'},
{n:'fibrothorax',f:'File:Fibrothorax chest x-ray.jpg',t:'纤维胸'},
{n:'hemothorax',f:'File:Massive right hemothorax.jpg',t:'大量右侧血胸'},
{n:'hemothorax',f:'File:Massive left hemothorax.jpg',t:'大量左侧血胸'},
{n:'hemothorax',f:'File:Hémothorax.jpg',t:'外伤性血胸'},
{n:'rib-fracture',f:'File:Rippenserienfraktur Röntgen Thorax.jpg',t:'多发肋骨骨折'},
{n:'rib-fracture',f:'File:Multiple Rib Fractures.jpg',t:'肋骨串联骨折'},
{n:'rib-fracture',f:'File:Rib fracture 2347.jpg',t:'单发肋骨骨折'},
{n:'lam',f:'File:Lymphangioleiomyomatose CT.jpg',t:'肺淋巴管肌瘤病'},
{n:'miliary-tb',f:'File:ZP miliar TBC (16).jpg',t:'粟粒性肺结核'},
{n:'round-pneumonia',f:'File:X1300068 Nevit.jpg',t:'儿童圆形肺炎'},
{n:'round-pneumonia',f:'File:Rad 1300155 cr.jpg',t:'圆形肺炎胸片'},
{o:'右侧气胸',f:'File:Deep sulcus sign 59jm - Roe - 001.jpg',t:'仰卧位气胸深沟征'},
{o:'气胸',f:'File:10-03-Pneumothorax CT coronar.png',t:'气胸冠状位CT'},
{o:'胸腔积液',f:'File:Pleural effusion CT axial WTF.jpg',t:'胸腔积液CT'},
{o:'胸腔积液',f:'File:14-02-Erguss im Stehen.png',t:'立位胸片少量胸腔积液'},
{o:'肺水肿',f:'File:Schmetterlingsoedem bei kardialer Dekompensation 64W - CR ap - 001.jpg',t:'蝶翼征心源性肺水肿'},
{o:'肺水肿',f:'File:18-01-Lungenoedem CT coronar.png',t:'肺水肿冠状位CT'},
{o:'肺动脉栓塞',f:'File:Reitender Thrombus bei Lungenembolie - CT - axial - 002.jpg',t:'骑跨型肺动脉血栓'},
{o:'肺不张',f:'File:Oberlappenatelektase links seitlich.jpg',t:'左上叶肺不张'},
{o:'肺不张',f:'File:Mittellappenatelektase CT sagittal.jpg',t:'右中叶肺不张'},
{o:'支气管扩张',f:'File:Massive Bronchiektasen - CT LF axial 001.jpg',t:'重度支气管扩张'},
{o:'支气管扩张',f:'File:Chest x-ray of bronchiectasis post-primary pulmonary tuberculosis.jpg',t:'结核后支气管扩张'},
{o:'肺气肿',f:'File:Medical X-Ray imaging WFH07 nevit.jpg',t:'肺气肿胸片'},
{o:'肺气肿',f:'File:Lung Volume Reduction Coils - chest - xray.jpg',t:'肺减容线圈术后影像'},
{o:'纵隔气肿',f:'File:Macklin-Effekt nach stumpfem Thoraxtrauma 53M - CT axial KM - 002.jpg',t:'Macklin效应纵隔气肿'},
{o:'纵隔气肿',f:'File:Mediastinalemphysem Perforation Oesophaguskarzinom.jpg',t:'食管癌穿孔相关纵隔气肿'},
{o:'肺脓肿',f:'File:ZP absces plic 2 (15).jpg',t:'空洞性肺脓肿'},
{o:'肺腺癌',f:'File:Adenokarzinom der Lunge im Roentgenbild 63M - CR pa - 001.jpg',t:'肺腺癌胸片'},
{o:'小细胞肺癌',f:'File:Metastasiertes kleinzelliges Lungenkarzinom 67W - CT KM pv - 001.jpg',t:'转移性小细胞肺癌'},
{o:'肺结节',f:'File:Chest x-ray of discrete nodule and volume loss.jpg',t:'肺结节伴肺容积减小'},
{o:'脓胸',f:'File:Pleuraempyem mit angrenzend konsolidierter Lunge 66M - CT axial KM - 001.jpg',t:'脓胸伴邻近肺实变'},
{o:'右位心',f:'File:Situs inversus chest Nevit.jpg',t:'全内脏反位伴右位心'},
{o:'肺隔离症',f:'File:Lungensequester rechter Unterlappen 20tW - CT KM arteriell - 001.jpg',t:'右下叶肺隔离症'},
{n:'lam',f:'File:Lymphangioleiomyomatose - CT axial LF.jpg',t:'肺淋巴管肌瘤病轴位CT'},
{o:'肺挫伤',f:'File:Lungenkontusion und -lazeration mit Pneumatozelen 40M - CT 3 Ebenen - 001.jpg',t:'肺挫伤伴裂伤和气囊肿'},
{o:'漏斗胸',f:'File:Trichterbrust in der Computertomografie 23M - CT axial und Volumen Rendering - 001.jpg',t:'漏斗胸CT与容积重建'},
{o:'贲门失弛缓症',f:'File:Achalasie im Breischluck 001.png',t:'贲门失弛缓症钡餐造影'},
{o:'过敏性肺炎',f:'File:Pneumonitis auf Everolimus - CT axial und coronar 001.jpg',t:'依维莫司相关药物性肺炎'}]),
...rows('神经',[
{n:'wilson',f:"File:Face of the giant panda sign in Wilson's disease.png",t:'Wilson病大熊猫脸征'},
{n:'pml',f:'File:MRI of patient with PML (32688495127).jpg',t:'进行性多灶性白质脑病'},
{n:'pml',f:'File:Progressive multifokale Leukenzephalopathie - MRT T2ax DWIax - 001.jpg',t:'PML的T2与DWI表现'},
{n:'adrenoleukodystrophy',f:'File:Adrenoleukodystrophy.jpg',t:'肾上腺脑白质营养不良'},
{n:'fahr',f:'File:Morbus Fahr 72M - CT - 001.jpg',t:'Fahr病双侧基底节钙化'},
{n:'cryptococcosis',f:'File:Cryptococcosis brain mri.jpg',t:'中枢神经系统隐球菌病'},
{n:'meningitis',f:'File:FLAIR MRI of meningitis.jpg',t:'脑膜炎FLAIR表现'},
{n:'subdural-empyema',f:'File:Subdural-empyema.jpg',t:'硬膜下脓肿'},
{n:'mca-infarct',f:'File:Right dense MCA sign as seen on CT brain.jpg',t:'大脑中动脉高密度征'},
{n:'pml',f:'File:Progressive multifokale Leukenzephalopathie - MRT T2ax T1cor - 001.jpg',t:'PML的T2与T1表现'},
{n:'venous-infarct',f:'File:Venous infarction brain mri.jpg',t:'脑静脉性梗死'},
{n:'pituitary-apoplexy',f:'File:Pituitary apoplexy.jpg',t:'垂体卒中'},
{n:'pituitary-apoplexy',f:'File:Hypophyseninfarkt mit Einblutung 44W - MR CT - 001.jpg',t:'垂体梗死伴出血'},
{n:'empty-sella',f:'File:Empty sella MRI.png',t:'空蝶鞍MRI'},
{n:'pineal-cyst',f:'File:Pinealiszyste 32jw - MRT T2 sag - 001.jpg',t:'松果体囊肿'},
{n:'pineal-cyst',f:'File:Maessig groessenprogrediente Pinealiszyste 10W - MR - 001.jpg',t:'进展性松果体囊肿'},
{n:'germinoma',f:'File:Tumor Germinoma PinealGland2.JPG',t:'松果体区生殖细胞瘤'},
{n:'germinoma',f:'File:Tumor Germinoma Suprasellar2.JPG',t:'鞍上生殖细胞瘤'},
{n:'ganglioglioma',f:'File:Desmoplastic infantile ganglioglioma.jpg',t:'促结缔组织增生性婴儿节细胞胶质瘤'},
{n:'myeloma-skull',f:'File:MMPlainSkull.png',t:'颅骨多发性骨髓瘤'},
{n:'craniofacial-fibrous-dysplasia',f:'File:Ausgedehnte kraniofaziale fibroese Dysplasie links partiell entlastet mit Kalottenersatz 76W - CT - 001.jpg',t:'广泛颅面骨纤维异常增殖症'},
{n:'craniofacial-fibrous-dysplasia',f:'File:Kranialfaziale fibroese Dysplasie 61M - CT und MRT - 001.jpg',t:'颅面骨纤维异常增殖症CT/MRI'},
{n:'superficial-siderosis',f:'File:Effective T2-weighted MRI of hemosiderin deposits after subarachnoid hemorrhage.png',t:'蛛网膜下腔出血后表面铁沉积'},
{n:'myeloma-skull',f:'File:Osteolytic Lesions.jpg',t:'颅骨多发性骨髓瘤多发溶骨灶'},
{o:'硬膜下血肿',f:'File:Subdurales Haematom MRT FLAIR axial.jpg',t:'硬膜下血肿FLAIR表现'},
{n:'germinoma',f:'File:Tumor Germinoma Suprasellar3.JPG',t:'鞍上生殖细胞瘤补充MRI'},
{o:'脑内出血',f:'File:Frontale Kontusionsblutung MRT HAEM 01.png',t:'额叶脑挫伤出血'},
{o:'蛛网膜下腔出血',f:'File:SAB bei Aneurysma.png',t:'动脉瘤性蛛网膜下腔出血'},
{o:'脑膜瘤',f:'File:Keilbeinmeningeom mit Oedem - CT - axial - 010.jpg',t:'蝶骨嵴脑膜瘤伴水肿'},
{o:'胶质母细胞瘤',f:'File:AFIP-00405590-Glioblastoma-Radiology.jpg',t:'胶质母细胞瘤影像表现'},
{o:'垂体腺瘤',f:'File:Makroadenom der Hypophyse 81W - CT sagittal - 001.jpg',t:'垂体大腺瘤'},
{o:'颅咽管瘤',f:'File:Craniopharyngioma-t1axkm-001.jpg',t:'颅咽管瘤增强MRI'},
{n:'empty-sella',f:'File:Empty Sella MRT T1KM cor 001.jpg',t:'空蝶鞍冠状位增强MRI'},
{o:'前庭神经鞘瘤',f:'File:Akustikus-Schwannon rechts MRT T1KM axial 002.jpg',t:'右侧前庭神经鞘瘤'},
{o:'脑动静脉畸形',f:'File:001 Arteriovenous Malformation CT axial 02.png',t:'脑动静脉畸形CT'},
{o:'发育性静脉异常',f:'File:Developmental venous anomaly MRT axial T1KM 01-01.jpg',t:'发育性静脉异常（海蛇头征）'},
{o:'发育性静脉异常',f:'File:Developmental Venous Anomaly MRT T1KM axial 02-01.jpg',t:'第二例发育性静脉异常'},
{o:'脑静脉窦血栓',f:'File:Sinusthrombose rechts Sinus transversalis 76W - MR - 001.jpg',t:'右侧横窦血栓'},
{o:'脑积水',f:'File:Langjaehrig bestehender Hydrocephalus 48M - CT - 001.jpg',t:'慢性脑积水'},
{o:'脑脓肿',f:'File:Ausgedehnte Hirnabszesse - verschiedene Wichtungen in der MRT 3M - MR - 001.jpg',t:'多发脑脓肿MRI'},
{o:'星形细胞瘤',f:'File:Pilozytisches Astrozytom WHO I vom linken Optikus - MRT - T2 axial - 011.jpg',t:'左侧视神经毛细胞型星形细胞瘤'},
{o:'髓母细胞瘤',f:'File:Medulloblastom - MRT - axial DWI - 003.jpg',t:'髓母细胞瘤DWI表现'},
{o:'Chiari I型畸形',f:'File:Chiari-Malformation MRT T2 sag.jpg',t:'Chiari I型畸形矢状位MRI'},
{o:'Sturge-Weber综合征',f:'File:Sturge-Weber-Syndrom bei einem Saeugling 5moM - MR - 001.jpg',t:'婴儿Sturge-Weber综合征'},
{o:'脊髓空洞症',f:'File:Syringohydromyelie und Diastematomyelie 42W - MR T2 axial - 001.jpg',t:'脊髓空洞症伴脊髓纵裂'},
{o:'弥漫性轴索损伤',f:'File:Diffuse axonal injury- cMRT nach 3 Tagen HAEM - Verlauf.jpg',t:'弥漫性轴索损伤MRI随访'},
{o:'颞部蛛网膜囊肿',f:'File:Temporale Arachnoidalzyste links MRT T1 coronar.jpg',t:'左颞部蛛网膜囊肿MRI'},
{o:'颞部蛛网膜囊肿',f:'File:Temporale Arachnoidalzyste rechts MRT T1 axial.jpg',t:'右颞部蛛网膜囊肿MRI'},
{o:'表皮样囊肿',f:'File:Epidermoidzyste MRT FLAIR ax.jpg',t:'表皮样囊肿FLAIR表现'},
{o:'室管膜瘤',f:'File:Anaplastisches Ependymom - MRT - T2 axial - 003.jpg',t:'间变性室管膜瘤'}]),
...rows('腹部',[
{n:'gallbladder-adenomyomatosis',f:'File:Ultrasound of gallbladder adenomyosis.jpg',t:'胆囊腺肌增生症超声'},
{n:'porcelain-gallbladder',f:'File:Porzellangallenblase - 88j - CT axial WT und KF - 001.jpg',t:'瓷化胆囊'},
{n:'porcelain-gallbladder',f:'File:Porzellangallenblase mit zusaetzlichen Konkrementen 85W - CT KM arteriell - 001.jpg',t:'瓷化胆囊伴结石'},
{n:'pancreas-divisum',f:'File:MRCP Pankreas divisum.jpg',t:'胰腺分裂MRCP'},
{n:'annular-pancreas',f:'File:Oesophagusatresie Typ III B und Duodenalstenose bei Pancreas anulare 0M - CR ap - 001.jpg',t:'环状胰腺伴十二指肠狭窄'},
{n:'annular-pancreas',f:'File:Double-Bubble-Zeichen bei Duodenalatresie und Pancreas anulare 1tW - CR ap - 001.jpg',t:'环状胰腺双泡征'},
{n:'serous-cystadenoma',f:'File:Serous cystadenoma of the pancreatic head..jpg',t:'胰头浆液性囊性肿瘤'},
{n:'ipmn',f:'File:IPMN MRCP MIP-00.jpg',t:'胰管内乳头状黏液性肿瘤MRCP'},
{n:'sma-syndrome',f:'File:Wilkie-Syndrom 19jm - CT cor und Roe ap - 001.jpg',t:'肠系膜上动脉综合征'},
{n:'sma-syndrome',f:'File:Wilkie -Syndrom - 49jw - DL - 001.jpg',t:'肠系膜上动脉综合征动态造影'},
{n:'meckel-diverticulum',f:'File:Meckel-Divertikel mit akut-entzuendlichen Veraenderungen 80W - CT coronar KM pv - 001.jpg',t:'炎性Meckel憩室'},
{n:'ulcerative-colitis',f:'File:Colitis ulcerosa - Haustrenverlust - Fahrradschlauch.jpg',t:'溃疡性结肠炎铅管征'},
{n:'ischemic-colitis',f:'File:Ischaemische Colitis 67W - CT - 001.jpg',t:'缺血性结肠炎'},
{n:'pneumatosis',f:'File:Pneumatosis intestinalis CT LF Darmischaemie.jpg',t:'肠壁积气伴肠缺血'},
{n:'splenic-cyst',f:'File:Verkalkte Milzzyste 63W - CT axial KM pv - 001.jpg',t:'钙化性脾囊肿'},
{n:'splenic-cyst',f:'File:Pseudozyste der Milz mit Randverkalkungen 83W - CT KM pv - 001.jpg',t:'脾假性囊肿伴壁钙化'},
{n:'splenic-abscess',f:'File:Abszess in der Milz bei Salmonella O - CT KM - 001.jpg',t:'脾脓肿'},
{n:'renal-lymphoma',f:'File:Ultrasonography of renal lymphoma.jpg',t:'肾淋巴瘤超声'},
{n:'bladder-diverticulum',f:'File:Sehr grosses Blasendivertikel im Ultraschall 58M - US - 001.jpg',t:'巨大膀胱憩室'},
{n:'ureterocele',f:'File:Ureterocele bei Doppelniere links - CT ax und cor.jpg',t:'重复肾伴输尿管囊肿'},
{o:'胆囊结石',f:'File:Ausgepraegte Cholecystolithiasis 68M - CT - 001.jpg',t:'多发胆囊结石CT'},
{o:'胆囊结石',f:'File:Sludge in der Gallenblase 80W - US - 001.jpg',t:'胆囊泥沙样沉积'},
{o:'腹主动脉瘤',f:'File:Rupturierendes Bauchaortenaneurysma 86W - CT axial und koronar - 001.jpg',t:'腹主动脉瘤破裂'},
{o:'急性胰腺炎',f:'File:Pankreatitis exsudativ CT axial.jpg',t:'渗出性急性胰腺炎'},
{o:'急性胰腺炎',f:'File:Pankreasschwanzpankreatitis 52M - CT axial und coronar KM pv - 001.jpg',t:'胰尾部急性胰腺炎'},
{o:'慢性胰腺炎',f:'File:Chronische Pankreatitis mit multiplen kleinen Verkalkungen 54M - CT KM arteriell - 001.jpg',t:'慢性钙化性胰腺炎'},
{o:'慢性胰腺炎',f:'File:Chronische Pankreatitis mit Rinnenpankreatitis 56M - CT KM pv - 001.jpg',t:'沟槽性胰腺炎'},
{o:'胰腺假性囊肿',f:'File:Pankreaspseudozyste mit enger Beziehung zum Magen 50M - CT - 001.jpg',t:'胰腺假性囊肿紧邻胃壁'},
{o:'胆总管结石',f:'File:MRCP Choledocholithiasis.jpg',t:'胆总管结石MRCP'},
{o:'胆管癌',f:'File:Klatskintumor-ERC.jpg',t:'肝门部胆管癌ERCP'},
{o:'门静脉高压',f:'File:Oesophagusvarizen 02.jpg',t:'门静脉高压伴食管静脉曲张'},
{o:'门静脉高压',f:'File:Portosystemische Umgehung CT VR 002.png',t:'门体侧支循环CT重建'},
{n:'gallbladder-adenomyomatosis',f:'File:Adenomyomatose der Gallenblase 71W - MR - 001.jpg',t:'胆囊腺肌增生症MRI'},
{o:'脾梗死',f:'File:Milzinfarkt 78W - CT axial KM pv - 001.jpg',t:'门静脉期楔形脾梗死'},
{o:'脾梗死',f:'File:Teilinfarkt der Milz 77W - CT axial KM pv - 001.jpg',t:'部分脾梗死'},
{o:'肝脓肿',f:'File:Leberabszess Klebsiella pneumoniae 72M - CT axial und coronar - 001.jpg',t:'肺炎克雷伯菌性肝脓肿'},
{o:'肝脓肿',f:'File:Leberabszesse bei Cholecystitis 71M - CT KM pv - 001.jpg',t:'胆囊炎并发多发肝脓肿'},
{o:'急性肾盂肾炎',f:'File:Pyelonephritis beidseits 51W - CT KM pv axial coronar - 001.jpg',t:'双侧急性肾盂肾炎'},
{o:'肾细胞癌',f:'File:Zystoides Nierenzellkarzinom 73W - CT axial und coronar KM pv - 001.jpg',t:'囊性肾细胞癌'},
{o:'肾血管平滑肌脂肪瘤',f:'File:Angiomyolipom der Niere Sonographie.jpg',t:'肾血管平滑肌脂肪瘤超声'},
{o:'肾结石',f:'File:Staghorn Kidney Stone 08779.jpg',t:'鹿角形肾结石'},
{o:'肾上腺髓样脂肪瘤',f:'File:Myelolipom der Nebenniere CT.jpg',t:'肾上腺髓样脂肪瘤CT'},
{o:'小肠梗阻',f:'File:Radiology 1300250.JPG',t:'机械性小肠梗阻'},
{o:'肠套叠',f:'File:Invagination 001 CT cor.png',t:'肠套叠冠状位CT'},
{o:'克罗恩病',f:'File:Duenndarmstenose Morbus Crohn KM-Passage 001.jpg',t:'克罗恩病小肠狭窄'},
{o:'肠系膜缺血',f:'File:Gas in Pfortaderaesten bei Mesenterialischaemie 90W - CT axial KM - 001.jpg',t:'肠系膜缺血伴门静脉积气'},
{o:'腹股沟疝',f:'File:Harnblase in Leistenhernie rechts 64M - CT axial und coronar - 001.jpg',t:'膀胱疝入右侧腹股沟'},
{o:'胃肠道间质瘤',f:'File:GIST des Oesophagus - CT axial - 001.jpg',t:'食管胃肠道间质瘤CT'},
{o:'门静脉血栓',f:'File:Pfortaderthrombose003.png',t:'门静脉血栓CT'},
{o:'腹膜脂垂炎',f:'File:Appendicitis epiploica CT coronar.png',t:'腹膜脂垂炎冠状位CT'}]),
...rows('骨骼',[
{n:'multiple-myeloma',f:'File:Plasmozytom multiple Osteolysen Unterarm.png',t:'多发性骨髓瘤前臂溶骨病灶'},
{n:'multiple-myeloma',f:'File:Diffuse Knochenmarkveraenderung bei multiplem Myelom 60W - MR T1 coronar - 001.jpg',t:'多发性骨髓瘤弥漫骨髓浸润'},
{n:'bone-metastases',f:'File:Lytic tumour proximal femur - 001.png',t:'股骨近端溶骨性转移瘤'},
{n:'bone-metastases',f:'File:ScleroticMets.PNG',t:'成骨性骨转移瘤'},
{n:'bone-metastases',f:'File:Pathologische Fraktur bei Metastase Nierencell-Ca im Humerus.jpg',t:'肾癌肱骨转移伴病理骨折'},
{n:'bone-metastases',f:'File:Osteoplastic bone metastasis prostate cancer 01.jpg',t:'前列腺癌成骨性骨转移'},
{n:'paget-bone',f:'File:Morbus Paget des Beckens rechts 77W - CR ap - 001.jpg',t:'骨Paget病（右侧骨盆）'},
{n:'brown-tumor',f:'File:Brown tumours of the hands.jpg',t:'甲状旁腺功能亢进性棕色瘤'},
{n:'renal-osteodystrophy',f:'File:X-ray of ground glass density of the skull by renal osteodystrophy.jpg',t:'肾性骨营养不良颅骨改变'},
{n:'osteopetrosis',f:'File:Osteopetrosis pelvis X-ray.png',t:'石骨症骨盆X线'},
{n:'osteopetrosis',f:'File:Osteopetrose mit bone-in-bone Erscheinungsbild vor allem an der HWS 19M - CR - 001.jpg',t:'石骨症骨中骨征'},
{n:'melorheostosis',f:'File:Melorheostose.jpg',t:'蜡泪样骨病'},
{n:'osteopoikilosis',f:'File:Osteopoikilie Haende.jpg',t:'骨斑点症（双手）'},
{n:'osteopoikilosis',f:'File:Osteopoikilie Fuss - 48jm - Roe 2Eb - 001.jpg',t:'骨斑点症（足部）'},
{n:'achondroplasia',f:'File:Deformierte Wirbelkoerper thorakolumbaler Uebergang bei Achondroplasie 2W - CR seitlich - 001.jpg',t:'软骨发育不全胸腰椎改变'},
{n:'osteogenesis-imperfecta',f:'File:XrayOITypeV-Audult.jpg',t:'成骨不全V型成人影像'},
{n:'osteogenesis-imperfecta',f:'File:XrayOITypeV-Kid.jpg',t:'成骨不全V型儿童影像'},
{n:'cleidocranial-dysplasia',f:'File:Cleidocranial.jpg',t:'锁骨颅骨发育不良'},
{n:'discitis',f:'File:Spondylodiscitis LWK 34 82M - MR und CT - 001.jpg',t:'腰椎椎间盘炎伴脊椎炎'},
{n:'cppd',f:'File:Chondrocalcinosis.jpg',t:'焦磷酸钙沉积病软骨钙化'},
{n:'cppd',f:'File:Crowned dens - 95jw - CT axial und coronar - 001.jpg',t:'冠齿综合征'},
{n:'erosive-osteoarthritis',f:'File:Erosive osteoarthritis with gull-wing appearance.jpg',t:'侵蚀性骨关节炎海鸥翼征'},
{n:'charcot-joint',f:'File:Charcotfuss - Roe 001.jpg',t:'Charcot足'},
{n:'boxer-fracture',f:'File:Boxers fracture.JPG',t:'拳击手骨折'},
{n:'bennett-fracture',f:"File:Bennet's fracture X-ray (1).jpg",t:'Bennett骨折'},
{n:'rolando-fracture',f:'File:Rolando-Fraktur 50M - CR 2 Ebenen und CT Volumen Rendering - 001.jpg',t:'Rolando骨折'},
{n:'mallet-finger',f:'File:Mallet Finger with fracture fragment.jpg',t:'骨性锤状指'},
{n:'tibial-plateau-fracture',f:'File:Segond-Fraktur 38jm - Roe und CT - 001.png',t:'Segond骨折'},
{n:'lisfranc-injury',f:'File:Lisfranc-Luxationsfraktur 22M - CR und Volumen Rendering aus CT-Datensatz - 001.jpg',t:'Lisfranc骨折脱位'},
{n:'jones-fracture',f:'File:Jonesfracture.jpg',t:'Jones骨折'},
{n:'calcaneal-fracture',f:'File:STIR MRI of of calcaneal fracture.jpg',t:'跟骨隐匿性骨折STIR表现'},
{n:'hip-labral-tear',f:'File:Sagittal T1 MRI of labral tear.jpg',t:'髋臼盂唇撕裂'},
{o:'髋部骨折',f:'File:PZ fraktura kyčelní kosti (40).jpg',t:'髋部骨折补充投照表现'},
{o:'踝部 Salter–Harris II 骨折',f:'File:Aitken-I-Fraktur der distalen Tibia 11W - CR und CT - 001.jpg',t:'儿童胫骨远端Salter-Harris II骨折'},
{o:'锁骨骨折',f:'File:Radiology 1300201.JPG',t:'锁骨骨折正位片'},
{o:'儿童桡骨远端隆起骨折',f:'File:Radiology 1300574 Nevit.jpg',t:'儿童桡骨远端隆起骨折侧位征象'},
{o:'肩关节后脱位',f:'File:Inverse Hill-Sachs-Laesion - posterior shoulder dislocation - CT axial und Roe 001.jpg',t:'肩关节后脱位伴反Hill-Sachs损伤'},
{o:'盂肱关节脱位',f:'File:Dislocated shoulder X-ray 03.png',t:'盂肱关节脱位正位征象'},
{o:'脊柱侧弯',f:'File:Surgical result after ventral fusion of scoliosis.jpg',t:'脊柱侧弯前路融合术后影像'},
{o:'Tillaux 骨折',f:'File:Tillaux-Fraktur 11jw - CT cor sag ax - 001.png',t:'青少年Tillaux骨折'},
{o:'肱骨骨折',f:'File:Okkulte Fraktur Humerus Roentgen MRT.jpg',t:'隐匿性肱骨骨折X线与MRI'},
{o:'舟骨骨折',f:'File:Scaphoid-Pseudarthrose1.jpg',t:'舟骨骨折不愈合'},
{o:'掌骨骨折',f:'File:MHK4-Fraktur 23j.png',t:'第四掌骨骨折'},
{o:'骨软骨瘤',f:'File:Kartilaginäre Exostose.png',t:'骨软骨瘤软骨帽征象'},
{o:'骨样骨瘤',f:'File:Osteoidosteom Roentgen-MRT.png',t:'骨样骨瘤X线与MRI'},
{o:'佝偻病',f:'File:Rad 1300118.JPG',t:'佝偻病干骺端改变'},
{o:'Legg-Calvé-Perthes病',f:'File:Morbus Perthes rechts 6W - CR ap - 001.jpg',t:'右侧Legg-Calvé-Perthes病'},
{o:'肩袖撕裂',f:'File:Neoartikulation subacromial 57W - Roe und MR PDW FS - 001.jpg',t:'慢性肩袖撕裂伴肩峰下假关节'},
{o:'肱二头肌腱断裂',f:'File:Bizepssehnenruptur distal MRT PDW FS.jpg',t:'肱二头肌远端肌腱断裂'},
{o:'软骨肉瘤',f:'File:Chondrosarkom proximaler Femur - 87jw - CT und Roe - 001.jpg',t:'股骨近端软骨肉瘤'}])];
if(PICKS.length!==200)throw new Error(`Expected 200 picks, got ${PICKS.length}`);
for(const s of ['胸部','神经','腹部','骨骼'])if(PICKS.filter(x=>x.system===s).length!==50)throw new Error(`${s} count`);
const currentFiles=['cases.js','curriculum.js','additional-groups.js','next-76-groups.js','expanded-cases.js'];const currentSource=(await Promise.all(currentFiles.map(f=>fs.readFile(path.join(ROOT,f),'utf8')))).join('\n').replace(', NEXT_200_GROUPS','');const current=JSON.parse(vm.runInNewContext(`const EXPANDED_CASE_SOURCES=${JSON.stringify(manifest.records)};\n${currentSource}\nJSON.stringify({cases:CASES,curriculum:CURRICULUM,groups:EXPANDED_GROUPS})`));
const diagnosis=c=>c.title.split(' · 开放病例')[0],idOf=c=>path.basename(c.image,path.extname(c.image));const lessonById=new Map(current.curriculum.map(x=>[x.id,x]));const sourceById=new Map(manifest.records.map(x=>[x.id,x]));
const baseByTitle=new Map();for(const c of current.cases){const src=sourceById.get(idOf(c));if(src&&!baseByTitle.has(diagnosis(c)))baseByTitle.set(diagnosis(c),src.groupKey)}
const candidateMaps={n:new Map(fresh.map(t=>[t.key.replace(/^(chest|neuro|abdomen|bone)-700-/,''),t])),o:new Map(alternates.map(t=>[`${t.system}:${t.zh}`,t]))};
const usedUrl=new Set(manifest.records.map(x=>x.sourceUrl)),usedSha=new Set(manifest.records.map(x=>x.originalSha1)),usedTitle=new Set(current.cases.map(diagnosis));const records=[],groups={};
{const seen=new Set(usedTitle);for(const p of PICKS){if(seen.has(p.t))throw new Error(`Duplicate teaching title ${p.t}`);seen.add(p.t)}}
const systems={胸部:'chest',神经:'neuro',腹部:'abdomen',骨骼:'bone'};
function infer(title,fallback){if(/MRCP|MRT|MRI|\bMR\b/i.test(title))return'MRI';if(/CT|CCT/i.test(title))return'CT';if(/Ultrasound|Sonograph|\bUS\b/i.test(title))return'US';if(/bone scan|scinti/i.test(title))return'骨显像';return fallback||'X-RAY'}
function generic(system,pick,topic,modality){const systemStep={胸部:'按气道、肺实质、胸膜、心纵隔和骨骼顺序复核',神经:'对称比较脑实质、脑室脑池、血管与颅骨',腹部:'结合增强时相或超声切面评估病变内部与周围反应',骨骼:'联合正交位检查皮质、小梁、关节对位与软组织'}[system];return{title:pick.t,english:topic.en,modality,level:'进阶',distractors:['同部位炎症或感染','同部位良性病变','同部位恶性或创伤性病变'],tags:[pick.t,modality,'定位','鉴别'],signs:[`识别与${pick.t}相符的核心影像分布和形态`,`核对病灶中心、范围及来源图像明确展示的伴随征象`,systemStep],basis:`公开来源明确将该影像标注为“${topic.zh}”相关表现；本例不补造未公开病史。`,differential:'先按病灶中心、边界、内部成分、分布和伴随改变建立鉴别，再结合完整序列与临床资料缩小范围。',pearl:`先客观描述图像，再提出${pick.t}；来源标签不能替代临床综合诊断。`,method:systemStep,next:'结合完整DICOM序列、既往影像和临床资料确认，必要时补充增强、实验室或病理检查。',tips:['遮住病例名称后先独立定位并描述。','单帧不能评价完整范围、强化动力学或精确测量。'],pitfalls:['不得从单张公开图片推断未展示的分期、病因或预后。','图像中的箭头和文字属于原始来源，不视为本站新增标注。'],recall:`定位 → 核对${pick.t}核心模式 → 鉴别 → 完整检查确认。`,ref:'acr'}}
function groupFromCase(baseCase){const lesson=lessonById.get(idOf(baseCase));return{title:diagnosis(baseCase),english:lesson?.english||diagnosis(baseCase),modality:baseCase.modality,level:baseCase.level||'进阶',distractors:(baseCase.options||[]).filter((_,i)=>i!==baseCase.answer),tags:[diagnosis(baseCase),baseCase.modality,baseCase.system],signs:baseCase.findings||[],basis:baseCase.explain||'',differential:baseCase.differential||'',pearl:baseCase.pearl||'',method:lesson?.method||'先定位，再描述形态与分布，最后结合完整检查建立鉴别。',next:lesson?.next||'结合完整检查、既往影像和临床资料确认。',tips:lesson?.tips||['先独立描述影像征象，再核对诊断。'],pitfalls:lesson?.pitfalls||['避免仅凭单张图片推断未展示的信息。'],recall:lesson?.recall||`定位 → ${diagnosis(baseCase)}核心征象 → 鉴别。`,ref:lesson?.ref||'acr'}}
async function download(url,attempt=0){try{const r=await fetch(url,{headers:{'User-Agent':'MedicalImagingLearningAudit/4.0 (https://github.com/a1553189184-stack/medical-imaging-learning)'}});if((r.status===429||r.status>=500)&&attempt<7){await new Promise(x=>setTimeout(x,2000*(attempt+1)));return download(url,attempt+1)}if(!r.ok)throw new Error(`${r.status} ${url}`);return Buffer.from(await r.arrayBuffer())}catch(error){if(attempt>=7)throw error;await new Promise(x=>setTimeout(x,2000*(attempt+1)));return download(url,attempt+1)}}
for(let i=0;i<PICKS.length;i++){const p=PICKS[i],topic=p.n?candidateMaps.n.get(p.n):candidateMaps.o.get(`${p.system}:${p.o}`);if(!topic)throw new Error(`Topic missing ${JSON.stringify(p)}`);const item=topic.candidates.find(x=>x.title===p.f);if(!item)throw new Error(`Candidate missing ${p.f}`);if(usedUrl.has(item.sourceUrl)||usedSha.has(item.originalSha1))throw new Error(`Duplicate source ${p.f}`);if(usedTitle.has(p.t))throw new Error(`Duplicate teaching title ${p.t}`);usedUrl.add(item.sourceUrl);usedSha.add(item.originalSha1);usedTitle.add(p.t);const prefix=systems[p.system],id=`${prefix}-700-${String(i%50+1).padStart(2,'0')}`,groupKey=id,bytes=await download(item.downloadUrl),png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if((!png&&!jpeg)||bytes.length<10000)throw new Error(`Invalid ${p.f}`);const image=`assets/images/expanded/${id}.${png?'png':'jpg'}`;await fs.writeFile(path.join(ROOT,...image.split('/')),bytes);const modality=infer(item.title,p.n?topic.modality:topic.modality);records.push({id,groupKey,system:p.system,image,sourceTitle:item.title.replace(/^File:/,''),sourceUrl:item.sourceUrl,sourceDescription:item.description,artist:item.artist,credit:item.credit,license:item.license,licenseUrl:item.licenseUrl,originalUrl:item.originalUrl,originalSha1:item.originalSha1,localSha256:crypto.createHash('sha256').update(bytes).digest('hex'),localBytes:bytes.length,width:item.width,height:item.height,mime:item.mime,retrieval:'curated-search-700',qualityScore:'source-and-contact-sheet-review'});if(p.o){const baseCase=current.cases.find(c=>diagnosis(c)===p.o),baseKey=baseByTitle.get(p.o),baseGroup=baseKey&&current.groups[baseKey]?current.groups[baseKey]:baseCase&&groupFromCase(baseCase);if(!baseGroup)throw new Error(`Base group missing ${p.o}`);groups[groupKey]={...baseGroup,title:p.t,english:`${lessonById.get(idOf(baseCase))?.english||baseGroup.english} — ${p.t}`,modality,basis:`公开来源明确支持“${p.o}”及病例标题所述表现；本例不补造未公开病史。`,recall:`定位 → ${p.t}核心征象 → 评估范围与并发症 → 完整检查确认。`}}else groups[groupKey]=generic(p.system,p,topic,modality);if((i+1)%10===0)console.log(`${i+1}/200`);await new Promise(x=>setTimeout(x,180))}
manifest.records.push(...records);manifest.count=manifest.records.length;manifest.generatedAt=new Date().toISOString();await fs.writeFile(manifestPath,JSON.stringify(manifest,null,2)+'\n');await fs.writeFile(path.join(ROOT,'next-200-groups.js'),`// Generated from the manually selected 700-case expansion.\nconst NEXT_200_GROUPS = ${JSON.stringify(groups,null,2)};\n`);console.log('done',manifest.count);
